title: Softik-RLF
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Matias Burgos"
  email: "someone@somewebsite.somedomain"
  url: "https://www.instagram.com/matiburg.osxd/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Matias Burgos"
year : "2022"
